import type { User, Session, ActivityFeedItemWithUser } from '@/types/database';

// Mock users for the group
export const MOCK_USERS: User[] = [
  {
    id: 'user-1',
    group_id: 'group-1',
    display_name: 'Du',
    avatar_url: null,
    email: null,
    goal_vr_hours: 9,
    goal_vansbro_minutes: 60,
    goal_lidingo_hours: 3,
    total_ep: 0,
    current_streak: 0,
    longest_streak: 0,
    streak_freezes_remaining: 1,
    created_at: '2026-02-28T00:00:00Z',
    updated_at: '2026-02-28T00:00:00Z',
  },
  {
    id: 'user-2',
    group_id: 'group-1',
    display_name: 'Erik',
    avatar_url: null,
    email: null,
    goal_vr_hours: 9,
    goal_vansbro_minutes: 60,
    goal_lidingo_hours: 3,
    total_ep: 87,
    current_streak: 3,
    longest_streak: 3,
    streak_freezes_remaining: 1,
    created_at: '2026-02-28T00:00:00Z',
    updated_at: '2026-02-28T00:00:00Z',
  },
  {
    id: 'user-3',
    group_id: 'group-1',
    display_name: 'Anna',
    avatar_url: null,
    email: null,
    goal_vr_hours: 9,
    goal_vansbro_minutes: 60,
    goal_lidingo_hours: 3,
    total_ep: 65,
    current_streak: 2,
    longest_streak: 4,
    streak_freezes_remaining: 1,
    created_at: '2026-02-28T00:00:00Z',
    updated_at: '2026-02-28T00:00:00Z',
  },
  {
    id: 'user-4',
    group_id: 'group-1',
    display_name: 'Johan',
    avatar_url: null,
    email: null,
    goal_vr_hours: 10,
    goal_vansbro_minutes: 70,
    goal_lidingo_hours: 3.5,
    total_ep: 42,
    current_streak: 1,
    longest_streak: 2,
    streak_freezes_remaining: 0,
    created_at: '2026-02-28T00:00:00Z',
    updated_at: '2026-02-28T00:00:00Z',
  },
];

// Mock logged sessions (updated_at omitted – will come from Supabase in production)
export const MOCK_SESSIONS: Session[] = [
  {
    id: 'session-1',
    user_id: 'user-2',
    planned_session_id: null,
    sport_type: 'cycling',
    date: '2026-02-28',
    duration_minutes: 45,
    distance_km: null,
    effort_rating: 3,
    note: 'Bra spinning, tungt i benen efter Vasaloppet!',
    ep_earned: 17,
    is_bonus: false,
    strava_activity_id: null,
    created_at: '2026-02-28T17:30:00Z',
    updated_at: '2026-02-28T17:30:00Z',
  },
  {
    id: 'session-2',
    user_id: 'user-3',
    planned_session_id: null,
    sport_type: 'running',
    date: '2026-02-28',
    duration_minutes: 30,
    distance_km: 4.5,
    effort_rating: 2,
    note: 'Lugn jogg i solen',
    ep_earned: 10,
    is_bonus: false,
    strava_activity_id: null,
    created_at: '2026-02-28T10:15:00Z',
    updated_at: '2026-02-28T10:15:00Z',
  },
  {
    id: 'session-3',
    user_id: 'user-2',
    planned_session_id: null,
    sport_type: 'running',
    date: '2026-03-01',
    duration_minutes: 35,
    distance_km: 5,
    effort_rating: 3,
    note: null,
    ep_earned: 13,
    is_bonus: false,
    strava_activity_id: null,
    created_at: '2026-03-01T08:00:00Z',
    updated_at: '2026-03-01T08:00:00Z',
  },
  {
    id: 'session-4',
    user_id: 'user-3',
    planned_session_id: null,
    sport_type: 'cycling',
    date: '2026-03-01',
    duration_minutes: 50,
    distance_km: null,
    effort_rating: 4,
    note: 'Tung spinning, kände mig stark!',
    ep_earned: 22,
    is_bonus: false,
    strava_activity_id: null,
    created_at: '2026-03-01T18:00:00Z',
    updated_at: '2026-03-01T18:00:00Z',
  },
  {
    id: 'session-5',
    user_id: 'user-4',
    planned_session_id: null,
    sport_type: 'hiit',
    date: '2026-03-01',
    duration_minutes: 30,
    distance_km: null,
    effort_rating: 5,
    note: 'Brutalt HIIT-pass',
    ep_earned: 12,
    is_bonus: false,
    strava_activity_id: null,
    created_at: '2026-03-01T12:00:00Z',
    updated_at: '2026-03-01T12:00:00Z',
  },
  {
    id: 'session-6',
    user_id: 'user-2',
    planned_session_id: null,
    sport_type: 'swimming',
    date: '2026-03-02',
    duration_minutes: 45,
    distance_km: null,
    effort_rating: 3,
    note: 'Crawlkurs, övade andning',
    ep_earned: 20,
    is_bonus: false,
    strava_activity_id: null,
    created_at: '2026-03-02T19:00:00Z',
    updated_at: '2026-03-02T19:00:00Z',
  },
];

// Mock activity feed
export const MOCK_FEED: ActivityFeedItemWithUser[] = [
  {
    id: 'feed-1',
    group_id: 'group-1',
    user_id: 'user-2',
    event_type: 'session_logged',
    event_data: { sport_type: 'swimming', duration: 45, ep: 20, note: 'Crawlkurs, övade andning' },
    created_at: '2026-03-02T19:00:00Z',
    updated_at: '2026-03-02T19:00:00Z',
    user: MOCK_USERS[1],
  },
  {
    id: 'feed-2',
    group_id: 'group-1',
    user_id: 'user-3',
    event_type: 'session_logged',
    event_data: { sport_type: 'cycling', duration: 50, ep: 22, note: 'Tung spinning' },
    created_at: '2026-03-01T18:00:00Z',
    updated_at: '2026-03-01T18:00:00Z',
    user: MOCK_USERS[2],
  },
  {
    id: 'feed-3',
    group_id: 'group-1',
    user_id: 'user-2',
    event_type: 'streak_milestone',
    event_data: { streak: 3 },
    created_at: '2026-03-01T08:05:00Z',
    updated_at: '2026-03-01T08:05:00Z',
    user: MOCK_USERS[1],
  },
  {
    id: 'feed-4',
    group_id: 'group-1',
    user_id: 'user-4',
    event_type: 'session_logged',
    event_data: { sport_type: 'hiit', duration: 30, ep: 12, note: 'Brutalt HIIT-pass' },
    created_at: '2026-03-01T12:00:00Z',
    updated_at: '2026-03-01T12:00:00Z',
    user: MOCK_USERS[3],
  },
  {
    id: 'feed-5',
    group_id: 'group-1',
    user_id: 'user-2',
    event_type: 'session_logged',
    event_data: { sport_type: 'running', duration: 35, ep: 13 },
    created_at: '2026-03-01T08:00:00Z',
    updated_at: '2026-03-01T08:00:00Z',
    user: MOCK_USERS[1],
  },
  {
    id: 'feed-6',
    group_id: 'group-1',
    user_id: 'user-3',
    event_type: 'session_logged',
    event_data: { sport_type: 'running', duration: 30, ep: 10, note: 'Lugn jogg i solen' },
    created_at: '2026-02-28T10:15:00Z',
    updated_at: '2026-02-28T10:15:00Z',
    user: MOCK_USERS[2],
  },
];

// Expedition waypoints along the Swedish route (created_at auto-set by DB)
export const EXPEDITION_WAYPOINTS = [
  { id: 1, name: 'Start – Mora', description: 'Vasaloppet avklarat! Expeditionen börjar.', ep_threshold: 0, map_x: 50, map_y: 20, sort_order: 1 },
  { id: 2, name: 'Rättvik', description: 'Genom Dalarna, förbi Siljan.', ep_threshold: 500, map_x: 55, map_y: 25, sort_order: 2 },
  { id: 3, name: 'Falun', description: 'Kopparstadens charm.', ep_threshold: 1000, map_x: 55, map_y: 30, sort_order: 3 },
  { id: 4, name: 'Gävle', description: 'Kusten närmar sig!', ep_threshold: 1500, map_x: 58, map_y: 35, sort_order: 4 },
  { id: 5, name: 'Uppsala', description: 'Universitetsstadens torn.', ep_threshold: 2000, map_x: 58, map_y: 42, sort_order: 5 },
  { id: 6, name: 'Stockholm', description: 'Huvudstaden! Halvvägs på resan.', ep_threshold: 2500, map_x: 62, map_y: 48, sort_order: 6 },
  { id: 7, name: 'Nyköping', description: 'Söderut längs kusten.', ep_threshold: 3000, map_x: 58, map_y: 55, sort_order: 7 },
  { id: 8, name: 'Linköping', description: 'Östgötaslätten breder ut sig.', ep_threshold: 3500, map_x: 52, map_y: 58, sort_order: 8 },
  { id: 9, name: 'Vadstena', description: 'Vid Vätterns strand!', ep_threshold: 4000, map_x: 48, map_y: 57, sort_order: 9 },
  { id: 10, name: 'Motala – Vätternrundan!', description: 'Dags att cykla runt Vättern! 315 km.', ep_threshold: 4500, map_x: 48, map_y: 55, sort_order: 10 },
  { id: 11, name: 'Karlstad', description: 'Västerut mot Värmland.', ep_threshold: 5000, map_x: 40, map_y: 48, sort_order: 11 },
  { id: 12, name: 'Vansbro – Simningen!', description: 'Hoppa i Vanån! 3 km.', ep_threshold: 5500, map_x: 42, map_y: 35, sort_order: 12 },
  { id: 13, name: 'Borlänge', description: 'Tillbaka genom Dalarna.', ep_threshold: 6000, map_x: 50, map_y: 32, sort_order: 13 },
  { id: 14, name: 'Västerås', description: 'Mälardalens pärla.', ep_threshold: 6500, map_x: 55, map_y: 40, sort_order: 14 },
  { id: 15, name: 'Lidingö – Loppet!', description: 'Sista racet! 30 km terränglöpning. Du är en Klassiker!', ep_threshold: 7000, map_x: 63, map_y: 47, sort_order: 15 },
];
